server:
  port: 8088

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  level:
    com.xyj.learn: debug

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.101:3306/test?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: Root!!123456

  devtools:
    restart:
      enabled: true


